os: osx

language: rust

install:
  - brew update
  - brew install python3

script:
  - cd curve
  - sh run.sh setup
  - sh run.sh setup_dev
  - sh run.sh build
  - sh run.sh test
  - sh run.sh lint
  - sh run.sh build_server
