os: osx

install:
  - brew update
  - brew install python3
  - brew install rust
  - brew install sdl2
  - brew install sdl2_ttf
  - brew install sdl2_image
  - brew install sdl2_mixer
  - brew install libpng
  - brew install libjpeg

script:
  - sh run.sh setup
  - sh run.sh setup dev
  - sh run.sh build
  - sh run.sh build server
  - sh run.sh test
  - sh run.sh test server
  - sh run.sh lint
  - sh run.sh check server
