jobs:
  build:
    docker:
      - image: python:3
    working_directory: ~/curve
    steps:
      - checkout

      - run:
          name: install dependencies
          command: apt-get update && apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libpng-dev libjpeg-dev
      
      - run:
          name: install rust
          command: apt-get update && apt-get install rustc cargo

      - run:
          name: setup
          command: sh run.sh setup

      - run:
          name: setup dev
          command: sh run.sh setup dev

      - run:
          name: build
          command: sh run.sh build

      - run:
          name: build server
          command: sh run.sh build server

      - run:
          name: test
          command: sh run.sh test

      - run:
          name: test server
          command: sh run.sh test server
      
      - run:
          name: lint
          command: sh run.sh lint

      - run:
          name: check server
          command: sh run.sh check server
