BLACK:
  R: 0
  G: 0
  B: 0
  A: 0

WHITE:
  R: 255
  G: 255
  B: 255
  A: 0

RED:
  R: 255
  G: 0
  B: 0
  A: 0

GREEN:
  R: 0
  G: 255
  B: 0
  A: 0

BLUE:
  R: 0
  G: 0
  B: 255
  A: 0

YELLOW:
  R: 242
  G: 238
  B: 0
  A: 0

ORANGE:
  R: 255
  G: 181
  B: 53
  A: 0
